version: 1.0.{build}
environment:
  choco_api_key:
    secure: XRbRwsYUh1rc3yuf9ZED76R8OgeKCGRSuD0pY0JClhuTOTOJERe7wJKxihWr+8/9
build: off
test_script:
- ps: >-
    choco pack

    choco install vibrancegui -s "$pwd" -f
deploy_script:
- IF DEFINED %APPVEYOR_REPO_TAG_NAME% choco apikey -k $env:choco_api_key -source https://chocolatey.org/
- IF DEFINED %APPVEYOR_REPO_TAG_NAME% choco push vibrancegui.2.3.1.1.nupkg -s https://chocolatey.org/
